### ISSUE TITLE
Add external metrics and graphs

### ISSUE THREAD

**Issue by calavera** [netlify/netlify-statuskit#1]
**- Do you want to request a *feature* or report a *bug*?**

This is a new feature.

**- What is the current behavior?**

There are no metrics or a way to create pretty graphs from external metrics :crying_cat_face: 

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

People should be able to give a set of metrics endpoints and configuration and we should put them in the landing page and a dedicated `/metrics/` page.

**Comment by steveoh** [comment]
I think this is beyond the scope of this project.
