### ISSUE TITLE
Add interactive command to create new incident.

### ISSUE THREAD

**Issue by calavera** [netlify/netlify-statuskit#16]
**- Do you want to request a *feature* or report a *bug*?**

This is a new feature.

**- What is the current behavior?**

You need to use hugo directly to create a new incident and then modify the frontMatter.

**- What is the expected behavior?**

I'd like to type something like `npm run new` and then be prompted with a series of questions, something like this:

```
prompt> npm run new
output > What the cause of the incident? 
input   > Connection issues in the load balancer
output > What's the severity of the incident? (degraded-performance, minor-outage, major-outage...)
input   >  minor-outage
output > What are the affected systems? (API, CDN, Origin servers...)
input   > CDN, Origin servers
output > Edit site/content/incidents/connection-issues-in-the-load-balancer.md ? (y/n)
input   > n
prompt>
```

The last question is not required, but having a prompt like this would make the process slightly faster and more convenient, specially to fill severity and affected systems.

**Comment by AmGarera** [comment]
I'd like to take a shot at this in the upcoming week when my time frees up

**Comment by steveoh** [comment]
FYI, I started this with #28 

![image](https://user-images.githubusercontent.com/325813/30090049-109269d2-926e-11e7-9435-d40504e91e97.png)

![image](https://user-images.githubusercontent.com/325813/30090061-1d9a6df0-926e-11e7-8f34-02a886c420a6.png)

**Comment by steveoh** [comment]
this can be closed also.
