### ISSUE TITLE
Should we add learning reviews section?

### ISSUE THREAD

**Issue by calavera** [netlify/netlify-statuskit#18]
**- Do you want to request a *feature* or report a *bug*?**

This is a new feature that I'm wondering about.

**- What is the current behavior?**

After an incident, we organize a learning review and put the outcome in a blog post. We usually update the incident with the link to this blog post.

**- What is the expected behavior?**

I'm wondering if it'd be more useful to add a learning reviews section to write those outcomes here.

**Comment by fool** [comment]
I vote yes, but i think it should be optional since we don't even have one for all of our incidents (eg ns1 degradation)

**Comment by RealGrim** [comment]
I vote yes!

**Comment by steveoh** [comment]
I think not. Update the incident with a link if you want to show this.
