### ISSUE TITLE
Incident Content missing in archetype incident.md

### ISSUE THREAD

**Issue by AgentGeek** [netlify/netlify-statuskit#30]
I tried to open new incident however i did successfully able to create new incident but i got stuck in incident content i tried finding out in archetype file but it don't have any content variable to define. Then i tried checking views files and found the the variable used in incident html template for description is {{- .Content -}} however i don't know why it didn't worked.

**Comment by steveoh** [comment]
Can you post some data. Your description is pretty slim on what went wrong and what you are trying to do?

**Comment by AgentGeek** [comment]
I meant for the image part it is not defined in incidents.md ![image](http://puu.sh/xxC7J/a85acff24d.png)

**Comment by dracos** [comment]
That is the main body of the markdown – you put markdown text under the final `+++` line (that is the end of what is called the `frontmatter`).

**Comment by steveoh** [comment]
i think this is user error. closing.
