### ISSUE TITLE
Cant create new indent with npm

### ISSUE THREAD

**Issue by RealGrim** [netlify/netlify-statuskit#36]
How do you create a issue i tried everything

**Comment by steveoh** [comment]
did you try `npm run new-incident` and what version of npm etc are you using? Did you npm install first? GIve some details

**Comment by RealGrim** [comment]
Yes i instaled github on my pc (I allready had git installed) then i installed npm and opend it in npm and yea i did run npm run new-incident but it just said this npm should be run outside of the node repl, in your normal shell.
(Press Control-D to exit.)

**Comment by steveoh** [comment]
So if you are in Windows open the cmd.exe and run it. What are you running it from now? Powershell?

**Comment by RealGrim** [comment]
Yes sorry for the late reply when i type npm in the search bar it comes up with node thats what im useing

**Comment by steveoh** [comment]
then your setup is wrong. when you type `npm` it should print the npm cli options.  Something like

```bash
$ npm

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami
```

If you type `npm -v` yo7 should see `5.6.0` or something like that.

When you type `node` you should enter the node repl. And `node -v` should show `v9.3.0` or something like that.

**Comment by RealGrim** [comment]
Is there a youtube vid that you can find how to do this

**Comment by RealGrim** [comment]
Ok yes when i use node.js in command promt it does show the availabe commands

**Comment by steveoh** [comment]
Its reading like your node and npm are backwards.

**Comment by RealGrim** [comment]
<img width="794" alt="capture" src="https://user-images.githubusercontent.com/34524489/34015160-a1a240e8-e0eb-11e7-9e58-358768e5c0d3.PNG">

**Comment by steveoh** [comment]
ok so type `npm run new-incident`

**Comment by RealGrim** [comment]
npm ERR! path C:\Users\Drew.DESKTOP-QR5AGAE\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Drew.DESKTOP-QR5AGAE\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Drew.DESKTOP-QR5AGAE\AppData\Roaming\npm-cache\_logs\2017-12-14T21_31_08_865Z-debug.log

**Comment by RealGrim** [comment]
Ok how do i do that?

**Comment by RealGrim** [comment]
How do i run it  or link it to the status kit folder i dont even have that on my pc

**Comment by RealGrim** [comment]
Ok its still not working i do know how to do it within the status kit folder

**Comment by steveoh** [comment]
Come talk in gitter. You need a lot of help. @verythorough close this because homer is super confused. Maybe update the docs that the cli is only for local dev or something?

**Comment by RealGrim** [comment]
Ok thank you
