### ISSUE TITLE
Fail wail deploying

### ISSUE THREAD

**Issue by RealGrim** [netlify/netlify-statuskit#39]
8:07:19 PM: Build ready to start
8:07:21 PM: Fetching cached dependencies
8:07:22 PM: Starting to download cache of 136.3MB
8:07:22 PM: Finished downloading cache in 789.099448ms
8:07:22 PM: Starting to extract cache
8:07:27 PM: Finished extracting cache in 4.456520615s
8:07:27 PM: Finished fetching cache in 5.372445741s
8:07:27 PM: Starting to prepare the repo for build
8:07:27 PM: Preparing Git Reference refs/heads/master
8:07:28 PM: Found netlify.toml. Overriding site configuration
8:07:28 PM: Running build command: npm run build
8:07:28 PM: Installing dependencies
8:07:31 PM: v6.12.2 is already installed.
8:07:32 PM: Now using node v6.12.2 (npm v3.10.10)
8:07:32 PM: Using version v6.12.2 of node
8:07:33 PM: Using /opt/buildhome/.rvm/gems/ruby-2.1.2
8:07:33 PM: mv: cannot move ‘/opt/build/cache/.yarn_cache’ to ‘/opt/build/.yarn_cache’
8:07:33 PM: : Permission denied
8:07:33 PM: Installing NPM modules using Yarn version 0.18.1
8:07:34 PM: yarn install v0.18.1
8:07:34 PM: error An unexpected error occurred: "EACCES: permission denied, mkdir '/opt/build/.yarn_cache'".
8:07:34 PM: info If you think this is a bug, please open a bug report with the information provided in "/opt/build/repo/yarn-error.log".
8:07:34 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
8:07:34 PM: Error during Yarn install
8:07:34 PM: Build complete: exit code: 1
8:07:34 PM: Error running command: Build script returned non-zero exit code: 1
8:07:34 PM: Failing build: Failed to build site
8:07:34 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
8:07:34 PM: Finished processing build request in 13.605933973

I am trying to create a 404 page i have it right but its failing!

**Comment by fool** [comment]
That was an error in Netlify's deploy process which has been fixed, not a bug in the statuskit.
