### ISSUE TITLE
Favicon not changing to -ok status

### ISSUE THREAD

**Issue by belazer** [netlify/netlify-statuskit#47]
Hello everyone,

I am currently experiencing the following bug:

I updated the favicons in the static folder and linked them in the config. Afterwards, I created a new incident (degraded performance) and the favicon changed to `-warning`. I resolved the issue but the favicon doesn't change to the `-ok` one. (Every incident has `resolved` set to true)

I would guess the issue has to lay somewhere in here:
```
{{ $active := where $incidents "Params.resolved" "!=" true }}

{{ if $major }}
      <link rel="icon" href="{{ absURL $favicons }}favicon-danger.ico">
    {{ else if $active }}
      <link rel="icon" href="{{ absURL $favicons }}favicon-warning.ico">
    {{ else }}
      <link rel="icon" href="{{ absURL $favicons }}favicon.ico">
```
If I output `$active` it says `Pages(1)`. To further investigate I deleted every incident.md and it changed to `Pages(0)` and the favicon changed as well. When I readd the .md's the favicon changes to warning again.

Here's the live example: https://status.graphcms.com/

What could be the problem here? Any suggestions?

**Comment by dracos** [comment]
Change `{{ $incidents := where .Site.Pages.ByDate.Reverse "Section" "incidents" }}` to `{{ $incidents := where .Site.RegularPages.ByDate.Reverse "Section" "incidents" }}` (as has already been done in index.html in 6dd1d6ab0576caa315edce0615aceff51a576d72).

**Comment by belazer** [comment]
Oh yeah, that was the issue! Thank you very much 🙂

**Comment by dracos** [comment]
If you wouldn't mind reopening, I'd leave this issue open until it is fixed in this repo :)

**Comment by steveoh** [comment]
pretty sure this was merged.

**Comment by dracos** [comment]
It is not fixed in current master. As I said above in https://github.com/netlify/netlify-statuskit/issues/47#issuecomment-360931318 it was fixed in index.html:
https://github.com/netlify/netlify-statuskit/blob/bfe3c1485ef73d7e809e298bb882407b1d411997/site/layouts/index.html#L3
but is not currently fixed in header.html:
https://github.com/netlify/netlify-statuskit/blob/bfe3c1485ef73d7e809e298bb882407b1d411997/site/layouts/partials/header.html#L8

**Comment by steveoh** [comment]
ok I misunderstood. this is now equal.
