### ISSUE TITLE
UptimeRobot integration

### ISSUE THREAD

**Issue by robsd** [netlify/netlify-statuskit#51]
**- Do you want to request a *feature* or report a *bug*?**
Feature
**- What is the current behavior?**
Have to manually update status page when server goes down, DDoS attack etc...
**- If the current behavior is a bug, please provide the steps to reproduce.**
N/a
**- What is the expected behavior?**
Would like to see some integration with UptimeRobot (using their API) to automatically create incidents/update the statuspage and leave us to fill in the blanks (investigating etc...)
**- Please mention your node.js, and operating system version.**
N/a

**Comment by steveoh** [comment]
I think this can be done with web hooks. I don't think this is a feature we will create.
