### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by mistermantas** [netlify/netlify-statuskit#56]
Quite a while ago, I started my [own project based on this](https://github.com/cstate/cstate) but I’m not even sure, if this is still receiving any reasonable updates, considering that Netlify itself switched away from Statuskit at some point in time for the status page most large-scale companies use?

**Comment by steveoh** [comment]
I have ownership... My agency uses the project but more in a maintenance mode than add new features etc. I am happy to bring in updates and review pr's.

**Comment by mistermantas** [comment]
As I've said previously, I'm the maker of cstate which does basically the same thing, arguably with more features. Thanks for the update, though!

**Comment by steveoh** [comment]
Is that an advertisement?
